// ─── Spendly Theme Presets ────────────────────────────────────────────────────
// Each theme defines the full color palette used across the app.

export const THEMES = {
  yellow: {
    id: 'yellow',
    name: 'Gold Rush',
    emoji: '⚡',
    primary:    '#FFD60A',
    secondary:  '#FF9500',
    accent:     '#70E000',
    background: '#FAFAFA',
    card:       '#FFFFFF',
    cardAlt:    '#F0F0F0',
    text:       '#000000',
    textMuted:  '#555555',
    border:     '#000000',
    shadow:     '#000000',
    danger:     '#FF4D4D',
    gridStroke: '#D1D5DB',
    dark:       false,
  },
  dark: {
    id: 'dark',
    name: 'Dark Mode',
    emoji: '🌑',
    primary:    '#FFD60A',
    secondary:  '#FF9500',
    accent:     '#70E000',
    background: '#111111',
    card:       '#1E1E1E',
    cardAlt:    '#2A2A2A',
    text:       '#FFFFFF',
    textMuted:  '#AAAAAA',
    border:     '#FFD60A',
    shadow:     '#FFD60A',
    danger:     '#FF4D4D',
    gridStroke: '#2E2E2E',
    dark:       true,
  },
  pink: {
    id: 'pink',
    name: 'Pink Babe',
    emoji: '🌸',
    primary:    '#FF6B9D',
    secondary:  '#FF8EC8',
    accent:     '#FF0080',
    background: '#FFF5F8',
    card:       '#FFFFFF',
    cardAlt:    '#FFE8F0',
    text:       '#000000',
    textMuted:  '#555555',
    border:     '#000000',
    shadow:     '#000000',
    danger:     '#FF4D4D',
    gridStroke: '#FFCCE0',
    dark:       false,
  },
  green: {
    id: 'green',
    name: 'Money Green',
    emoji: '💚',
    primary:    '#00E87A',
    secondary:  '#80FFD5',
    accent:     '#00B459',
    background: '#F5FFFB',
    card:       '#FFFFFF',
    cardAlt:    '#EAFFF5',
    text:       '#000000',
    textMuted:  '#445544',
    border:     '#000000',
    shadow:     '#000000',
    danger:     '#FF4D4D',
    gridStroke: '#C0FFE8',
    dark:       false,
  },
  purple: {
    id: 'purple',
    name: 'Purple Gang',
    emoji: '💜',
    primary:    '#BF5FFF',
    secondary:  '#E0B0FF',
    accent:     '#9B00FF',
    background: '#FBF5FF',
    card:       '#FFFFFF',
    cardAlt:    '#F0E0FF',
    text:       '#000000',
    textMuted:  '#554466',
    border:     '#000000',
    shadow:     '#000000',
    danger:     '#FF4D4D',
    gridStroke: '#E8CCFF',
    dark:       false,
  },
  blue: {
    id: 'blue',
    name: 'Ocean Blue',
    emoji: '🌊',
    primary:    '#0099FF',
    secondary:  '#66BBFF',
    accent:     '#0055CC',
    background: '#F0F8FF',
    card:       '#FFFFFF',
    cardAlt:    '#DCF0FF',
    text:       '#000000',
    textMuted:  '#334455',
    border:     '#000000',
    shadow:     '#000000',
    danger:     '#FF4D4D',
    gridStroke: '#CCE5FF',
    dark:       false,
  },
};

export const THEME_ORDER = ['yellow', 'dark', 'pink', 'green', 'purple', 'blue'];

export default THEMES;
